#!/usr/bin/env node
/* ES-module bundler: static/js/*.js -> static/dist/enhancements.bundle.js
 * Usage:
 *   npm i -D esbuild
 *   node tools/build.mjs
 *
 * The runtime does NOT require this bundle. Individual modules in static/js/
 * are loaded directly via <script defer> in app.py. Use the bundle in
 * production setups that want a single minified file. To switch, replace the
 * individual <script defer src="/static/js/*.js"> tags in app.py with:
 *   <script defer src="/static/dist/enhancements.bundle.js"></script>
 */
import { build } from "esbuild";
import { readdirSync, promises as fs } from "node:fs";
import { join } from "node:path";

const srcDir = "static/js";
const outFile = "static/dist/enhancements.bundle.js";

// Load order matches the <script defer> tags in app.py.
const ORDER = [
  "core-dom.js",
  "companies.js", "samples.js",
  "accounts.js", "partners.js", "registry.js", "convert.js", "dialogs.js",
  "toast.js", "theme.js", "preview.js", "filter.js",
  "mobile-tables.js", "validation.js", "combobox.js", "registry-retry.js",
  // Iteration 6 enhancements
  "undo.js", "bulk-ops.js", "shortcuts.js", "i18n.js",
  "dropzone.js", "recent-files.js", "field-help.js", "onboarding.js",
  "error-row-jump.js", "import-profiles.js", "audit-log.js",
  "export-summary.js", "diff-view.js", "pwa-register.js",
];

const present = new Set(readdirSync(srcDir));
const entries = ORDER.filter(n => present.has(n)).map(n => join(srcDir, n));
const missing = ORDER.filter(n => !present.has(n));
if (missing.length) console.warn("skipped (missing):", missing.join(", "));

async function run() {
  await fs.mkdir("static/dist", { recursive: true });
  const parts = [];
  for (const f of entries) {
    const r = await build({
      entryPoints: [f], write: false, minify: true, target: "es2020",
      logLevel: "warning",
    });
    parts.push(`/* ${f} */\n` + r.outputFiles[0].text);
  }
  await fs.writeFile(outFile,
    "/* Banki UI bundle - generated by tools/build.mjs */\n" + parts.join("\n"));
  console.log(`wrote ${outFile} (${parts.length} modules)`);
}
run().catch(e => { console.error(e); process.exit(1); });
